-- CreateTable
CREATE TABLE "DANHSACHTHUPHI" (
    "MADOTTHU" INTEGER NOT NULL,
    "MAHOKHAU" INTEGER NOT NULL,
    "TENDONGTIEN" TEXT,
    "TENLOAIPHI" TEXT,
    "TIENNHA" DECIMAL(18,2),
    "TIENDICHVU" DECIMAL(18,2),
    "TIENXEMAY" DECIMAL(18,2),
    "TIENOTO" DECIMAL(18,2),
    "TENDIEN" TEXT,
    "SODIEN" DECIMAL(18,2),
    "TENNUOC" TEXT,
    "SONUOC" DECIMAL(18,2),
    "TIENINTERNET" DECIMAL(18,2),
    "TRANGTHAI" VARCHAR(50),
    "SOTIENDADONG" DECIMAL(18,2),
    "NGAYDONG" TIMESTAMP(3),

    CONSTRAINT "DANHSACHTHUPHI_pkey" PRIMARY KEY ("MADOTTHU","MAHOKHAU")
);

-- CreateTable
CREATE TABLE "DONGGOP" (
    "MADONGGOP" SERIAL NOT NULL,
    "MADOTTHU" INTEGER,
    "MAHOKHAU" INTEGER,
    "MALOAIPHI" INTEGER,
    "SOTIENDADONG" DECIMAL(18,2),
    "TRANGTHAI" VARCHAR(50),
    "NGAYDONG" TIMESTAMP(3),
    "TENCHUHO" TEXT,

    CONSTRAINT "DONGGOP_pkey" PRIMARY KEY ("MADONGGOP")
);

-- CreateTable
CREATE TABLE "DOTTHUPHI" (
    "MADOTTHU" SERIAL NOT NULL,
    "TEN" TEXT NOT NULL,
    "BATBUOC" BOOLEAN NOT NULL DEFAULT true,
    "NGAYTAO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "MOTA" TEXT,

    CONSTRAINT "DOTTHUPHI_pkey" PRIMARY KEY ("MADOTTHU")
);

-- CreateTable
CREATE TABLE "FEETHUHO" (
    "MADOTTHU" INTEGER NOT NULL,
    "MAHOKHAU" INTEGER NOT NULL,
    "TONGDIEN" DECIMAL(18,2),
    "TONGTIENDIEN" DECIMAL(18,2),
    "TONGNUOC" DECIMAL(18,2),
    "TONGTIENNUOC" DECIMAL(18,2),
    "THANHTIENNUOC" DECIMAL(18,2),
    "THANHTIENINTERNET" DECIMAL(18,2),

    CONSTRAINT "FEETHUHO_pkey" PRIMARY KEY ("MADOTTHU","MAHOKHAU")
);

-- CreateTable
CREATE TABLE "HOKHAU" (
    "MAHOKHAU" SERIAL NOT NULL,
    "IDCHUHO" INTEGER NOT NULL,
    "DIACHI" TEXT,
    "NGAYTAO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "GHICHU" TEXT,
    "TENCHUHO" TEXT NOT NULL,
    "XEMAY" INTEGER DEFAULT 0,
    "OTO" INTEGER DEFAULT 0,
    "MAPHONG" VARCHAR(20) NOT NULL,
    "TRANGTHAI" BOOLEAN NOT NULL DEFAULT true,
    "LOAICANHO" VARCHAR(50) NOT NULL,
    "ACTIVATE" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "HOKHAU_pkey" PRIMARY KEY ("MAHOKHAU")
);

-- CreateTable
CREATE TABLE "LOAIPHI" (
    "MALOAIPHI" SERIAL NOT NULL,
    "TEN" TEXT NOT NULL,
    "BATBUOC" BOOLEAN NOT NULL DEFAULT true,
    "SOTIENTRENNGUOITRENTHANG" DECIMAL(18,2),
    "NGAYTAO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "MOTA" TEXT,

    CONSTRAINT "LOAIPHI_pkey" PRIMARY KEY ("MALOAIPHI")
);

-- CreateTable
CREATE TABLE "NGUOIQUANLY" (
    "TENDANGNHAP" VARCHAR(50) NOT NULL,
    "HOTEN" TEXT NOT NULL,
    "MATKHAU" VARCHAR(255) NOT NULL,
    "SODIENTHOAI" VARCHAR(15) NOT NULL,
    "VAITRO" VARCHAR(50),

    CONSTRAINT "NGUOIQUANLY_pkey" PRIMARY KEY ("TENDANGNHAP")
);

-- CreateTable
CREATE TABLE "NHANKHAU" (
    "MANHANKHAU" SERIAL NOT NULL,
    "MAHOKHAU" INTEGER,
    "HOTEN" TEXT NOT NULL,
    "SOCANCUOC" VARCHAR(20),
    "NGAYSINH" DATE,
    "GIOITINH" VARCHAR(10),
    "NOISINH" TEXT,
    "NGUYENQUAN" TEXT,
    "DANTOC" VARCHAR(30),
    "TONGIAO" VARCHAR(30),
    "QUOCTICH" VARCHAR(50),
    "NOITHUONGTRU" TEXT,
    "NGHENGHIEP" TEXT,
    "NGAYTAO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "QUANHEVOICHUHO" VARCHAR(50),
    "GHICHU" TEXT,
    "ACTIVATE" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "NHANKHAU_pkey" PRIMARY KEY ("MANHANKHAU")
);

-- CreateTable
CREATE TABLE "PHICODINH" (
    "LOAICANHO" VARCHAR(50) NOT NULL,
    "GIATIENCANHO" DECIMAL(18,2),
    "PHIQLCHUNGCU" DECIMAL(18,2),
    "PHIKEDAP" DECIMAL(18,2),
    "PHIXEOTO" DECIMAL(18,2),

    CONSTRAINT "PHICODINH_pkey" PRIMARY KEY ("LOAICANHO")
);

-- CreateTable
CREATE TABLE "TAMTRU" (
    "MADANGKYTAMTRU" SERIAL NOT NULL,
    "MANHANKHAU" INTEGER NOT NULL,
    "SODIENTHOAINGUOIDANGKY" VARCHAR(15),
    "TUNGAY" DATE,
    "DENNGAY" DATE,
    "LYDO" TEXT,

    CONSTRAINT "TAMTRU_pkey" PRIMARY KEY ("MADANGKYTAMTRU")
);

-- CreateTable
CREATE TABLE "TAMVANG" (
    "MADANGKYTAMVANG" SERIAL NOT NULL,
    "MANHANKHAU" INTEGER NOT NULL,
    "NOTAMTRU" TEXT,
    "TUNGAY" DATE,
    "DENNGAY" DATE,
    "LYDO" TEXT,

    CONSTRAINT "TAMVANG_pkey" PRIMARY KEY ("MADANGKYTAMVANG")
);

-- CreateIndex
CREATE UNIQUE INDEX "NHANKHAU_SOCANCUOC_key" ON "NHANKHAU"("SOCANCUOC");

-- AddForeignKey
ALTER TABLE "DANHSACHTHUPHI" ADD CONSTRAINT "DANHSACHTHUPHI_MADOTTHU_fkey" FOREIGN KEY ("MADOTTHU") REFERENCES "DOTTHUPHI"("MADOTTHU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DANHSACHTHUPHI" ADD CONSTRAINT "DANHSACHTHUPHI_MAHOKHAU_fkey" FOREIGN KEY ("MAHOKHAU") REFERENCES "HOKHAU"("MAHOKHAU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DONGGOP" ADD CONSTRAINT "DONGGOP_MADOTTHU_fkey" FOREIGN KEY ("MADOTTHU") REFERENCES "DOTTHUPHI"("MADOTTHU") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DONGGOP" ADD CONSTRAINT "DONGGOP_MAHOKHAU_fkey" FOREIGN KEY ("MAHOKHAU") REFERENCES "HOKHAU"("MAHOKHAU") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DONGGOP" ADD CONSTRAINT "DONGGOP_MALOAIPHI_fkey" FOREIGN KEY ("MALOAIPHI") REFERENCES "LOAIPHI"("MALOAIPHI") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FEETHUHO" ADD CONSTRAINT "FEETHUHO_MADOTTHU_fkey" FOREIGN KEY ("MADOTTHU") REFERENCES "DOTTHUPHI"("MADOTTHU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FEETHUHO" ADD CONSTRAINT "FEETHUHO_MAHOKHAU_fkey" FOREIGN KEY ("MAHOKHAU") REFERENCES "HOKHAU"("MAHOKHAU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HOKHAU" ADD CONSTRAINT "HOKHAU_IDCHUHO_fkey" FOREIGN KEY ("IDCHUHO") REFERENCES "NHANKHAU"("MANHANKHAU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HOKHAU" ADD CONSTRAINT "HOKHAU_LOAICANHO_fkey" FOREIGN KEY ("LOAICANHO") REFERENCES "PHICODINH"("LOAICANHO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NHANKHAU" ADD CONSTRAINT "NHANKHAU_MAHOKHAU_fkey" FOREIGN KEY ("MAHOKHAU") REFERENCES "HOKHAU"("MAHOKHAU") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TAMTRU" ADD CONSTRAINT "TAMTRU_MANHANKHAU_fkey" FOREIGN KEY ("MANHANKHAU") REFERENCES "NHANKHAU"("MANHANKHAU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TAMVANG" ADD CONSTRAINT "TAMVANG_MANHANKHAU_fkey" FOREIGN KEY ("MANHANKHAU") REFERENCES "NHANKHAU"("MANHANKHAU") ON DELETE RESTRICT ON UPDATE CASCADE;
