/*
  Warnings:

  - You are about to drop the `FEETHUHO` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropForeignKey
ALTER TABLE "public"."FEETHUHO" DROP CONSTRAINT "FEETHUHO_MADOTTHU_fkey";

-- DropForeignKey
ALTER TABLE "public"."FEETHUHO" DROP CONSTRAINT "FEETHUHO_MAHOKHAU_fkey";

-- DropTable
DROP TABLE "public"."FEETHUHO";

-- CreateTable
CREATE TABLE "PHITHUHO" (
    "MADOTTHU" INTEGER NOT NULL,
    "MAHOKHAU" INTEGER NOT NULL,
    "TONGDIEN" DECIMAL(18,2),
    "TONGTIENDIEN" DECIMAL(18,2),
    "TONGNUOC" DECIMAL(18,2),
    "TONGTIENNUOC" DECIMAL(18,2),
    "THANHTIENNUOC" DECIMAL(18,2),
    "THANHTIENINTERNET" DECIMAL(18,2),

    CONSTRAINT "PHITHUHO_pkey" PRIMARY KEY ("MADOTTHU","MAHOKHAU")
);

-- AddForeignKey
ALTER TABLE "PHITHUHO" ADD CONSTRAINT "PHITHUHO_MADOTTHU_fkey" FOREIGN KEY ("MADOTTHU") REFERENCES "DOTTHUPHI"("MADOTTHU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PHITHUHO" ADD CONSTRAINT "PHITHUHO_MAHOKHAU_fkey" FOREIGN KEY ("MAHOKHAU") REFERENCES "HOKHAU"("MAHOKHAU") ON DELETE RESTRICT ON UPDATE CASCADE;
