-- AlterTable
ALTER TABLE "DOTTHUPHI" ADD COLUMN     "NGAYBATDAU" TIMESTAMP(3),
ADD COLUMN     "NGAYKETTHUC" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "LICHSU_CUTRU" ADD COLUMN     "MAPHONG" TEXT;

-- AlterTable
ALTER TABLE "PHITHUHO" ADD COLUMN     "DONGIADIEN" DECIMAL(18,2),
ADD COLUMN     "DONGIANUOC" DECIMAL(18,2);
