/*
  Warnings:

  - You are about to drop the column `TENDIEN` on the `DANHSACHTHUPHI` table. All the data in the column will be lost.
  - You are about to drop the column `TENNUOC` on the `DANHSACHTHUPHI` table. All the data in the column will be lost.
  - The `TRANGTHAI` column on the `DANHSACHTHUPHI` table would be dropped and recreated. This will lead to data loss if there is data in the column.
  - You are about to drop the column `TENCHUHO` on the `DONGGOP` table. All the data in the column will be lost.
  - The `TRANGTHAI` column on the `DONGGOP` table would be dropped and recreated. This will lead to data loss if there is data in the column.
  - You are about to drop the column `TENCHUHO` on the `HOKHAU` table. All the data in the column will be lost.
  - You are about to drop the column `TRANGTHAI` on the `HOKHAU` table. All the data in the column will be lost.
  - You are about to drop the column `PHIKEDAP` on the `PHICODINH` table. All the data in the column will be lost.
  - You are about to drop the column `NOTAMTRU` on the `TAMVANG` table. All the data in the column will be lost.

*/
-- DropForeignKey
ALTER TABLE "public"."DANHSACHTHUPHI" DROP CONSTRAINT "DANHSACHTHUPHI_MADOTTHU_fkey";

-- DropForeignKey
ALTER TABLE "public"."DONGGOP" DROP CONSTRAINT "DONGGOP_MADOTTHU_fkey";

-- DropForeignKey
ALTER TABLE "public"."DONGGOP" DROP CONSTRAINT "DONGGOP_MALOAIPHI_fkey";

-- DropForeignKey
ALTER TABLE "public"."HOKHAU" DROP CONSTRAINT "HOKHAU_IDCHUHO_fkey";

-- DropForeignKey
ALTER TABLE "public"."HOKHAU" DROP CONSTRAINT "HOKHAU_LOAICANHO_fkey";

-- DropForeignKey
ALTER TABLE "public"."PHITHUHO" DROP CONSTRAINT "PHITHUHO_MADOTTHU_fkey";

-- AlterTable
ALTER TABLE "DANHSACHTHUPHI" DROP COLUMN "TENDIEN",
DROP COLUMN "TENNUOC",
ADD COLUMN     "GHICHU" TEXT,
ADD COLUMN     "HINHTHUC" TEXT,
ADD COLUMN     "TIENDIEN" DECIMAL(18,2),
ADD COLUMN     "TIENNUOC" DECIMAL(18,2),
ALTER COLUMN "TENDONGTIEN" SET DEFAULT 'VND',
DROP COLUMN "TRANGTHAI",
ADD COLUMN     "TRANGTHAI" BOOLEAN DEFAULT false;

-- AlterTable
ALTER TABLE "DONGGOP" DROP COLUMN "TENCHUHO",
ADD COLUMN     "GHICHU" TEXT,
ADD COLUMN     "HINHTHUC" TEXT,
ADD COLUMN     "TENDONGTIEN" TEXT DEFAULT 'VND',
DROP COLUMN "TRANGTHAI",
ADD COLUMN     "TRANGTHAI" BOOLEAN DEFAULT false;

-- AlterTable
ALTER TABLE "HOKHAU" DROP COLUMN "TENCHUHO",
DROP COLUMN "TRANGTHAI",
ADD COLUMN     "NGAYKETTHUC" TIMESTAMP(3),
ALTER COLUMN "IDCHUHO" DROP NOT NULL;

-- AlterTable
ALTER TABLE "NHANKHAU" ADD COLUMN     "NGAYKETTHUC" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "PHICODINH" DROP COLUMN "PHIKEDAP",
ADD COLUMN     "PHIXEMAY" DECIMAL(18,2);

-- AlterTable
ALTER TABLE "TAMVANG" DROP COLUMN "NOTAMTRU",
ADD COLUMN     "NOITAMTRU" TEXT;

-- CreateTable
CREATE TABLE "LICHSU_CUTRU" (
    "ID" SERIAL NOT NULL,
    "MANHANKHAU" INTEGER NOT NULL,
    "MAHOKHAU" INTEGER,
    "LOAITHAYDOI" TEXT,
    "NGAYBATDAU" TIMESTAMP(3) NOT NULL,
    "NGAYKETTHUC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CHUCVU_CU" TEXT,
    "GHI_CHU" TEXT,

    CONSTRAINT "LICHSU_CUTRU_pkey" PRIMARY KEY ("ID")
);

-- AddForeignKey
ALTER TABLE "DANHSACHTHUPHI" ADD CONSTRAINT "DANHSACHTHUPHI_MADOTTHU_fkey" FOREIGN KEY ("MADOTTHU") REFERENCES "DOTTHUPHI"("MADOTTHU") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DONGGOP" ADD CONSTRAINT "DONGGOP_MADOTTHU_fkey" FOREIGN KEY ("MADOTTHU") REFERENCES "DOTTHUPHI"("MADOTTHU") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DONGGOP" ADD CONSTRAINT "DONGGOP_MALOAIPHI_fkey" FOREIGN KEY ("MALOAIPHI") REFERENCES "LOAIPHI"("MALOAIPHI") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PHITHUHO" ADD CONSTRAINT "PHITHUHO_MADOTTHU_fkey" FOREIGN KEY ("MADOTTHU") REFERENCES "DOTTHUPHI"("MADOTTHU") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HOKHAU" ADD CONSTRAINT "HOKHAU_IDCHUHO_fkey" FOREIGN KEY ("IDCHUHO") REFERENCES "NHANKHAU"("MANHANKHAU") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "HOKHAU" ADD CONSTRAINT "HOKHAU_LOAICANHO_fkey" FOREIGN KEY ("LOAICANHO") REFERENCES "PHICODINH"("LOAICANHO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LICHSU_CUTRU" ADD CONSTRAINT "LICHSU_CUTRU_MANHANKHAU_fkey" FOREIGN KEY ("MANHANKHAU") REFERENCES "NHANKHAU"("MANHANKHAU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LICHSU_CUTRU" ADD CONSTRAINT "LICHSU_CUTRU_MAHOKHAU_fkey" FOREIGN KEY ("MAHOKHAU") REFERENCES "HOKHAU"("MAHOKHAU") ON DELETE SET NULL ON UPDATE CASCADE;
